name: Daily Mock Release

on: push
#   schedule:
#     - cron: '*/6 * * * *'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate version number
        id: version
        run: echo "version=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Generate release notes
        id: notes
        run: |
          npm install faker
          echo "notes=$(npx faker.lorem.paragraphs 3)%0A%0A%0A$(date +'%B %d, %Y')" >> $GITHUB_OUTPUT

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: ${{ steps.version.outputs.version }}
          body: ${{ steps.notes.outputs.notes }}
          draft: false
          prerelease: false
